title    SevenOS Live (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=0 rd.systemd.show_status=false systemd.show_status=false systemd.log_level=err rd.udev.log_level=0 udev.log_priority=0 vt.global_cursor_default=0 plymouth.ignore-serial-consoles nvidia_drm.modeset=1 ibt=off
