title    SevenOS Live Safe Graphics (%ARCH%, UEFI)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% nvidia_drm.modeset=1 nouveau.modeset=1 i915.modeset=1 amdgpu.dc=1 ibt=off loglevel=4 systemd.show_status=true vt.global_cursor_default=1
