---
dontChroot: true
timeout: 60
verbose: true

script:
  - command: "/bin/bash /usr/local/bin/seven-calamares-livecleanup-target ${ROOT}"
    timeout: 120

i18n:
  name: "Preparing SevenOS user environment"
  name[fr]: "Préparation de l'environnement utilisateur SevenOS"
