---
dontChroot: false
timeout: 60
verbose: true

script:
  - "-/usr/bin/pkill -u seven"
  - "-/usr/bin/userdel -r seven"
  - "-/usr/bin/groupdel seven"
  - "-/usr/bin/systemctl disable sevenos-live-session.service"
  - "-/bin/rm -f /etc/systemd/system/sevenos-live-session.service"
  - "-/bin/rm -f /etc/systemd/system/getty@tty1.service.d/20-sevenos-live-autologin.conf"
  - "-/bin/rm -f /etc/sddm.conf.d/20-sevenos-live.conf"
  - "-/bin/rm -f /usr/share/wayland-sessions/sevenos-live.desktop"
  - "-/bin/rm -f /home/seven/.bash_profile"

i18n:
  name: "Preparing SevenOS user environment"
  name[fr]: "Préparation de l'environnement utilisateur SevenOS"
