---
unpack:
  - source: "/run/archiso/airootfs"
    sourcefs: "file"
    destination: ""
    weight: 100
    exclude:
      - "/dev/*"
      - "/proc/*"
      - "/sys/*"
      - "/run/*"
      - "/tmp/*"
      - "/mnt/*"
      - "/media/*"
      - "/lost+found"
      - "/var/cache/pacman/pkg/*"
      - "/var/tmp/*"
