local M = {
  schema = "sevenos.hypr-lua.keybinds.v1",
  phase = "common-keybind-rules",
}

M.common_binds = {
  "bind = $mod, Return, exec, $terminal",
  "bind = $mod SHIFT, Return, exec, seven-terminal profile",
  "bind = $mod CTRL, Return, exec, seven-terminal menu",
  "bindr = $mod, SUPER_L, exec, $launcher",
  "bindr = $mod, SUPER_R, exec, $launcher",
  "bind = $mod, SPACE, exec, $spotlight",
  "bind = $mod, A, exec, $launcher",
  "bind = $mod, C, exec, seven shield mode",
  "bind = $mod, TAB, exec, $overview",
  "bind = $mod, N, exec, $quicksettings",
  "bind = $mod, O, exec, $quicksettings",
  "bind = $mod, comma, exec, $settings",
  "bind = $mod, I, exec, seven-settings general",
  "bind = $mod, D, exec, $dock",
  "bind = $mod, T, exec, /opt/SevenOS/bin/seven-tools",
  "bind = $mod, t, exec, /opt/SevenOS/bin/seven-tools",
  "bind = $mod, W, exec, $spotlight",
  "bind = $mod CTRL, W, exec, seven widgets menu",
  "bind = $mod, E, exec, seven-files",
  "bind = $mod SHIFT, E, exec, seven-files menu",
  "bind = $mod CTRL, E, exec, seven-files profile",
  "bind = $mod, H, exec, seven-help-native",
  "bind = $mod SHIFT, H, exec, seven-hub",
  "bind = $mod, R, exec, $spotlight",
  "bind = $mod SHIFT, P, exec, seven-power",
  "bind = $mod, L, exec, seven-power lock",
  "bind = $mod SHIFT, L, exec, systemctl suspend || loginctl suspend",
  "bind = $mod SHIFT, R, exec, sh -lc 'PATH=\"$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH\"; seven-recorder area'",
  "bind = $mod CTRL SHIFT, R, exec, sh -lc 'PATH=\"$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH\"; seven-recorder full'",
  "bind = $mod ALT, R, exec, hyprctl reload",
  "bind = $mod, Q, killactive",
  "bind = $mod, M, exit",
  "bind = $mod, F, exec, seven-window fullscreen",
  "bind = $mod SHIFT, F, exec, seven-window smart-maximize",
  "bind = $mod ALT, SPACE, exec, seven-window toggle-float",
  "bind = $mod ALT, L, exec, seven-window layout-menu",
  "bind = $mod ALT, D, exec, seven-window controls-toggle",
  "bind = $mod CTRL ALT, D, exec, seven-window controls",
  "bind = $mod, V, exec, seven-overview windows",
  "bind = $mod, P, pseudo",
  "bind = $mod, S, togglespecialworkspace, seven",
  "bind = $mod ALT, S, movetoworkspace, special:seven",
  "bind = $mod, left, movefocus, l",
  "bind = $mod, right, movefocus, r",
  "bind = $mod, up, movefocus, u",
  "bind = $mod, down, movefocus, d",
  "bind = $mod SHIFT, left, movewindow, l",
  "bind = $mod SHIFT, right, movewindow, r",
  "bind = $mod SHIFT, up, movewindow, u",
  "bind = $mod SHIFT, down, movewindow, d",
  "bind = $mod, 1, exec, seven-workspace switch 1",
  "bind = $mod, 2, exec, seven-workspace switch 2",
  "bind = $mod, 3, exec, seven-workspace switch 3",
  "bind = $mod, 4, exec, seven-workspace switch 4",
  "bind = $mod, 5, exec, seven-workspace switch 5",
  "bind = $mod, 6, exec, seven-workspace switch 6",
  "bind = $mod, 7, exec, seven-workspace switch 7",
  "bind = $mod, 8, exec, seven-workspace switch 8",
  "bind = $mod, 9, exec, seven-workspace switch 9",
  "bind = $mod SHIFT, 1, movetoworkspace, 1",
  "bind = $mod SHIFT, 2, movetoworkspace, 2",
  "bind = $mod SHIFT, 3, movetoworkspace, 3",
  "bind = $mod SHIFT, 4, movetoworkspace, 4",
  "bind = $mod SHIFT, 5, movetoworkspace, 5",
  "bind = $mod SHIFT, 6, movetoworkspace, 6",
  "bind = $mod SHIFT, 7, movetoworkspace, 7",
  "bind = $mod SHIFT, 8, movetoworkspace, 8",
  "bind = $mod SHIFT, 9, movetoworkspace, 9",
  "bind = $mod CTRL, right, exec, seven-workspace next",
  "bind = $mod CTRL, left, exec, seven-workspace prev",
  "bind = $mod, Page_Down, exec, seven-workspace next",
  "bind = $mod, Page_Up, exec, seven-workspace prev",
  "bind = $mod SHIFT, Page_Down, movetoworkspace, r+1",
  "bind = $mod SHIFT, Page_Up, movetoworkspace, r-1",
  "bind = , Print, exec, seven-screenshot area save",
  "bind = $mod, Print, exec, seven-screenshot full save",
  "bind = $mod SHIFT, S, exec, seven-screenshot area edit",
  "bind = $mod CTRL, S, exec, seven-screenshot area copy",
  "bind = $mod SHIFT, C, exec, hyprpicker -a || true",
  "bind = $mod SHIFT, I, exec, hyprsysteminfo || seven doctor check system",
  "bind = $mod SHIFT, U, exec, seven hypr status",
  "bind = $mod CTRL, C, exec, seven shield hud",
  "bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ -l 1.5",
  "bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-",
  "bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
  "bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%",
  "bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-",
}

M.mouse_binds = {
  "bindm = $mod, mouse:272, movewindow",
  "bindm = $mod, mouse:273, resizewindow",
}

M.launchpad_modal_binds = {
  "submap = sevenos-launchpad",
  "bind = , Escape, exec, hyprctl dispatch submap reset; pkill -f 'seven-launchpad-native' || true",
  "bindr = $mod, SUPER_L, exec, hyprctl dispatch submap reset; pkill -f 'seven-launchpad-native' || true",
  "bindr = $mod, SUPER_R, exec, hyprctl dispatch submap reset; pkill -f 'seven-launchpad-native' || true",
  "submap = reset",
}

function M.rules()
  local out = {}
  for _, rule in ipairs(M.common_binds) do out[#out + 1] = rule end
  for _, rule in ipairs(M.mouse_binds) do out[#out + 1] = rule end
  for _, rule in ipairs(M.launchpad_modal_binds) do out[#out + 1] = rule end
  return out
end

return M
