# SevenOS Kitty
# African first terminal surface: obsidian, gold, clay, baobab, raffia.

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.5
disable_ligatures never

cursor_shape beam
cursor_blink_interval 0.55
cursor_stop_blinking_after 12.0

scrollback_lines 12000
wheel_scroll_multiplier 3.0
touch_scroll_multiplier 3.0
mouse_hide_wait 2.0
copy_on_select no
strip_trailing_spaces smart
enable_audio_bell no
visual_bell_duration 0.08

window_padding_width 10
single_window_margin_width 0
remember_window_size yes
initial_window_width 112c
initial_window_height 34c
confirm_os_window_close 0
resize_debounce_time 0.08

background_opacity 0.91
dynamic_background_opacity yes
background_blur 14
dim_opacity 0.72

tab_bar_edge top
tab_bar_margin_width 8.0
tab_bar_margin_height 6.0 0.0
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template " {index}: {title} "
active_tab_title_template " {index}: {title} "
active_tab_font_style bold
inactive_tab_font_style normal

wayland_titlebar_color background
linux_display_server wayland

foreground #e8dcc3
background #0b0b0a
selection_foreground #0b0b0a
selection_background #d6a84f

cursor #d6a84f
cursor_text_color #0b0b0a
url_color #d6a84f

active_border_color #d6a84f
inactive_border_color #24180f
bell_border_color #9b4a2f

active_tab_foreground #0b0b0a
active_tab_background #d6a84f
inactive_tab_foreground #b7a98a
inactive_tab_background #15130f
tab_bar_background #0b0b0a

mark1_foreground #0b0b0a
mark1_background #d6a84f
mark2_foreground #0b0b0a
mark2_background #456b4f
mark3_foreground #0b0b0a
mark3_background #9b4a2f

# ANSI palette
color0  #0b0b0a
color1  #9b4a2f
color2  #456b4f
color3  #d6a84f
color4  #26344f
color5  #8f5f8f
color6  #5f8f86
color7  #e8dcc3
color8  #15130f
color9  #c86445
color10 #6c9875
color11 #e3bd68
color12 #4b628f
color13 #b888ad
color14 #82b7ad
color15 #fff3d8

# Ergonomic defaults
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback fzf
map ctrl+shift+backspace clear_terminal reset active

detect_urls yes
open_url_with default
url_style curly

shell_integration enabled
