return {
  key = "baobab",
  title = "Baobab Immersion OS",
  role = "African cultural immersion and transmission space",
  workspace_policy = "roots-memory-stage-field",
  ui_density = "calm",
  runtime_signals = {
    context = "african-cultural-immersion",
    layout = "roots-memory-sound-fieldwork",
    priority = "daily-ritual-offline-transmission",
  },
  workspace_intent = {
    "1: Racines - Baobab home, route, ritual and immersion focus",
    "2: Mémoire - heritage, reading, languages and living archive",
    "3: Scène - soundscape, narration, music and oral transmission",
    "4: Terrain - countries, collection, packs and community review",
  },
  actions = {
    "prefer Baobab native immersion as the primary surface",
    "route Seven Reader as a cultural learning tool",
    "surface daily ritual and route before generic apps",
    "keep offline-first cultural memory available",
    "avoid developer, gaming or security assumptions",
  },
  env_rules = {
    "env = SEVENOS_HYPR_PROFILE,baobab",
    "env = SEVENOS_HYPR_LAYOUT,culture",
  },
  layout_rules = {
    "general {",
    "    gaps_in = 9",
    "    gaps_out = 18",
    "    border_size = 1",
    "    layout = dwindle",
    "    resize_on_border = true",
    "}",
    "decoration {",
    "    dim_inactive = true",
    "    dim_strength = 0.04",
    "}",
  },
  animation_rules = {
    "animations {",
    "    animation = workspaces, 1, 9, sevenWorkspace, slidefade 22%",
    "    animation = windows, 1, 7, sevenOpen, popin 88%",
    "}",
  },
  window_rules = {
    "windowrule = match:class ^(SevenReaderNative)$, workspace 2",
    "windowrule = match:title ^(Seven Reader)$, workspace 2",
    "windowrule = match:class ^(foliate|com.github.johnfactotum.Foliate)$, workspace 2",
    "windowrule = match:class ^(vlc|mpv)$, workspace 3",
    "windowrule = match:title ^(Baobab|Baobab OS|Baobab Cultural Mini OS|Baobab Modules)$, workspace 1",
    "windowrule = match:title ^(Baobab Sound)$, workspace 3",
  },
}
