return {
  key = "baobab",
  title = "Baobab Cultural OS",
  role = "African cultural mini OS",
  workspace_policy = "village-heritage-story-map",
  ui_density = "calm",
  runtime_signals = {
    context = "african-cultural-village",
    layout = "heritage-story-sound-map",
    priority = "offline-cultural-transmission",
  },
  workspace_intent = {
    "1: Baobab Village, daily culture and heritage dashboard",
    "2: Heritage Library, reading, archives and oral traditions",
    "3: Cultural Stage, soundscape, radio, narration and media",
    "4: Africa Map, atelier, food, fashion and community memory",
  },
  actions = {
    "prefer Baobab Village as the primary surface",
    "route Seven Reader as a primary learning tool",
    "keep offline-first cultural memory available",
    "avoid developer, gaming or security assumptions",
  },
  env_rules = {
    "env = SEVENOS_HYPR_PROFILE,baobab",
    "env = SEVENOS_HYPR_LAYOUT,culture",
  },
  layout_rules = {
    "general {",
    "    gaps_in = 7",
    "    gaps_out = 14",
    "    border_size = 1",
    "    layout = dwindle",
    "    resize_on_border = true",
    "}",
    "decoration {",
    "    dim_inactive = true",
    "    dim_strength = 0.04",
    "}",
  },
  animation_rules = {
    "animations {",
    "    animation = workspaces, 1, 8, sevenWorkspace, slidefade 28%",
    "    animation = windows, 1, 6, sevenOpen, popin 84%",
    "}",
  },
  window_rules = {
    "windowrule = match:class ^(SevenReaderNative)$, workspace 2",
    "windowrule = match:title ^(Seven Reader)$, workspace 2",
    "windowrule = match:class ^(foliate|com.github.johnfactotum.Foliate)$, workspace 2",
    "windowrule = match:class ^(vlc|mpv)$, workspace 3",
    "windowrule = match:title ^(Baobab|Baobab Cultural Mini OS|Baobab Modules)$, workspace 1",
  },
}
