#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="${SEVENOS_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
MANIFEST="${SEVENOS_MANIFEST:-$ROOT_DIR/sevenos.dotinst}"
OUT_DIR="${SEVENOS_PACKAGE_OUT:-$ROOT_DIR/packaging/pacman}"

usage() {
  cat <<'EOF'
Usage: scripts/package-plan.sh <command>

Commands:
  plan          Print SevenOS package boundaries.
  generate     Generate local PKGBUILD skeletons from sevenos.dotinst.
  doctor       Validate generated packaging metadata.
  clean        Remove generated packaging output.
EOF
}

manifest_python() {
  python - "$MANIFEST" "$ROOT_DIR" "$OUT_DIR" "$@" <<'PY'
import json
import os
import shutil
import sys
from pathlib import Path

manifest_path = Path(sys.argv[1])
root = Path(sys.argv[2])
out_dir = Path(sys.argv[3])
command = sys.argv[4]

with manifest_path.open("r", encoding="utf-8") as handle:
    manifest = json.load(handle)

version = str(manifest.get("version", "0.0.0")).split("-", 1)[0]
source = manifest.get("source", "")

runtime_deps = {
    "sevenos-cli": ["bash", "python", "pacman"],
    "sevenos-branding": ["bash", "librsvg"],
    "sevenos-hyprland": ["hyprland", "waybar", "rofi", "kitty", "mako", "swayidle", "swaylock"],
    "sevenos-shell": ["gjs", "typescript", "gtk4", "libadwaita", "libgtop"],
    "sevenos-hub": ["gtk4", "libadwaita", "python-gobject", "webkit2gtk-4.1", "nodejs", "npm"],
    "sevenos-profiles": ["bash", "pacman"],
    "sevenos-server": ["python", "curl"],
    "sevenos-installer": ["archiso", "archinstall"],
}

def components():
    return manifest.get("components", [])

def plan():
    print("SevenOS package plan")
    for component in components():
        cid = component.get("id")
        print(f"\n{cid}")
        print(f"  title: {component.get('title')}")
        print(f"  deps: {', '.join(runtime_deps.get(cid, ['bash']))}")
        for path in component.get("paths", []):
            print(f"  - {path}")

def pkgbuild(component):
    cid = component.get("id")
    title = component.get("title", cid)
    paths = component.get("paths", [])
    deps = " ".join(f"'{item}'" for item in runtime_deps.get(cid, ["bash"]))
    install_lines = []
    for item in paths:
        src = root / item
        if not src.exists():
            raise SystemExit(f"missing component path for {cid}: {item}")
        target = f"usr/share/sevenos/{item}"
        if src.is_dir():
            install_lines.append(f'  cp -a "$srcdir/SevenOS/{item}" "$pkgdir/usr/share/sevenos/{item.rsplit("/", 1)[0] if "/" in item else ""}"')
        else:
            install_lines.append(f'  install -Dm755 "$srcdir/SevenOS/{item}" "$pkgdir/usr/share/sevenos/{target.removeprefix("usr/share/sevenos/")}"')

    script_links = []
    for item in paths:
        if item.startswith("bin/"):
            name = Path(item).name
            script_links.append(f'  ln -sf "/usr/share/sevenos/{item}" "$pkgdir/usr/bin/{name}"')

    lines = [
        "# Generated by scripts/package-plan.sh. Review before publishing.",
        f"pkgname={cid}",
        f"pkgver={version}",
        "pkgrel=1",
        f'pkgdesc="{title} for SevenOS"',
        "arch=('any')",
        f'url="{source}"',
        "license=('MIT')",
        f"depends=({deps})",
        "source=('SevenOS::git+https://github.com/seven-v73/SevenOS.git')",
        "sha256sums=('SKIP')",
        "",
        "package() {",
        '  install -d "$pkgdir/usr/share/sevenos"',
        '  install -d "$pkgdir/usr/bin"',
    ]
    lines.extend(install_lines)
    lines.extend(script_links)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)

def generate():
    out_dir.mkdir(parents=True, exist_ok=True)
    for component in components():
        cid = component.get("id")
        package_dir = out_dir / cid
        package_dir.mkdir(parents=True, exist_ok=True)
        (package_dir / "PKGBUILD").write_text(pkgbuild(component), encoding="utf-8")
        (package_dir / "README.md").write_text(
            f"# {cid}\n\nGenerated SevenOS package skeleton for `{component.get('title')}`.\n\nReview the PKGBUILD before publishing.\n",
            encoding="utf-8",
        )
    print(f"Generated {len(components())} package skeletons in {out_dir}")

def doctor():
    problems = []
    if not out_dir.is_dir():
        problems.append(f"missing output dir: {out_dir}")
    for component in components():
        cid = component.get("id")
        pkgbuild_path = out_dir / cid / "PKGBUILD"
        if not pkgbuild_path.is_file():
            problems.append(f"missing PKGBUILD: {cid}")
            continue
        content = pkgbuild_path.read_text(encoding="utf-8")
        if f"pkgname={cid}" not in content:
            problems.append(f"PKGBUILD pkgname mismatch: {cid}")
        if "package()" not in content:
            problems.append(f"PKGBUILD missing package(): {cid}")
    if problems:
        for problem in problems:
            print(f"package-plan: {problem}", file=sys.stderr)
        raise SystemExit(1)
    print("SevenOS package plan OK")
    print(f"packages: {len(components())}")

def clean():
    if out_dir.exists():
        shutil.rmtree(out_dir)
    print(f"Removed {out_dir}")

if command == "plan":
    plan()
elif command == "generate":
    generate()
elif command == "doctor":
    doctor()
elif command == "clean":
    clean()
else:
    raise SystemExit(f"unknown command: {command}")
PY
}

command="${1:-plan}"
case "$command" in
  plan|generate|doctor|clean)
    manifest_python "$command"
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
