#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="${SEVENOS_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CONFIG_HOME/sevenos"
THEME_CONF="$STATE_DIR/theme.conf"
RUNTIME_ENV="$STATE_DIR/theme-runtime.env"
HYPR_THEME_ENV="$CONFIG_HOME/hypr/conf/sevenos-theme-env.conf"

theme_pref() {
  local mode=""
  if [[ -r "$THEME_CONF" ]]; then
    mode="$(awk -F= 'tolower($1) ~ /^(mode|theme_mode|sevenos_theme_mode)$/ {gsub(/[[:space:]"]/, "", $2); print tolower($2); exit}' "$THEME_CONF" 2>/dev/null || true)"
  fi
  if [[ "$mode" == "light" || "$mode" == "dark" ]]; then
    printf '%s' "$mode"
  else
    printf 'dark'
  fi
}

runtime_mode() {
  if [[ -r "$RUNTIME_ENV" ]]; then
    awk -F= 'tolower($1) == "sevenos_theme_mode" {gsub(/[[:space:]"]/, "", $2); print tolower($2); exit}' "$RUNTIME_ENV" 2>/dev/null || true
  fi
}

runtime_value() {
  local key="$1"
  if [[ -r "$RUNTIME_ENV" ]]; then
    awk -F= -v wanted="$key" 'tolower($1) == tolower(wanted) {gsub(/^[[:space:]"]+|[[:space:]"]+$/, "", $2); print $2; exit}' "$RUNTIME_ENV" 2>/dev/null || true
  fi
}

gtk_ini_value() {
  local key="$1"
  local file="$CONFIG_HOME/gtk-3.0/settings.ini"
  [[ -r "$file" ]] || return 0
  awk -F= -v wanted="$key" '$1 == wanted {print $2; exit}' "$file" 2>/dev/null || true
}

hypr_env_value() {
  local key="$1"
  [[ -r "$HYPR_THEME_ENV" ]] || return 0
  awk -F= -v wanted="$key" '
    $1 ~ /env[[:space:]]*/ {
      split($2, parts, ",")
      gsub(/[[:space:]]/, "", parts[1])
      if (parts[1] == wanted) {
        sub(/^[^,]*,/, "", $2)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)
        print $2
        exit
      }
    }
  ' "$HYPR_THEME_ENV" 2>/dev/null || true
}

sync_env() {
  local mode color_scheme
  mode="$(theme_pref)"
  color_scheme="prefer-dark"
  [[ "$mode" == "light" ]] && color_scheme="prefer-light"

  if [[ -r "$RUNTIME_ENV" ]]; then
    # shellcheck disable=SC1090
    source "$RUNTIME_ENV" || true
  fi

  export SEVENOS_THEME_MODE="${SEVENOS_THEME_MODE:-$mode}"
  export GTK_THEME="${SEVENOS_GTK_THEME:-${GTK_THEME:-adw-gtk3}}"
  export QT_QPA_PLATFORMTHEME="${QT_QPA_PLATFORMTHEME:-qt6ct}"
  export QT_STYLE_OVERRIDE="${QT_STYLE_OVERRIDE:-kvantum}"
  export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-Hyprland}"
  export XDG_SESSION_TYPE="${XDG_SESSION_TYPE:-wayland}"
  export ELECTRON_OZONE_PLATFORM_HINT="${ELECTRON_OZONE_PLATFORM_HINT:-auto}"

  mkdir -p "$(dirname -- "$HYPR_THEME_ENV")"
  {
    printf '# Generated by SevenOS theme-session. Do not edit by hand.\n'
    printf 'env = SEVENOS_THEME_MODE,%s\n' "$SEVENOS_THEME_MODE"
    printf 'env = GTK_THEME,%s\n' "$GTK_THEME"
    printf 'env = QT_QPA_PLATFORMTHEME,%s\n' "$QT_QPA_PLATFORMTHEME"
    printf 'env = QT_STYLE_OVERRIDE,%s\n' "$QT_STYLE_OVERRIDE"
    printf 'env = XDG_CURRENT_DESKTOP,%s\n' "$XDG_CURRENT_DESKTOP"
    printf 'env = XDG_SESSION_TYPE,%s\n' "$XDG_SESSION_TYPE"
    printf 'env = ELECTRON_OZONE_PLATFORM_HINT,auto\n'
    printf 'env = SEVENOS_COLOR_SCHEME,%s\n' "$color_scheme"
  } > "$HYPR_THEME_ENV"

  if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface color-scheme "$color_scheme" >/dev/null 2>&1 || true
    [[ -n "${SEVENOS_GTK_THEME:-}" ]] && gsettings set org.gnome.desktop.interface gtk-theme "$SEVENOS_GTK_THEME" >/dev/null 2>&1 || true
    [[ -n "${SEVENOS_ICON_THEME:-}" ]] && gsettings set org.gnome.desktop.interface icon-theme "$SEVENOS_ICON_THEME" >/dev/null 2>&1 || true
    [[ -n "${SEVENOS_CURSOR_THEME:-}" ]] && gsettings set org.gnome.desktop.interface cursor-theme "$SEVENOS_CURSOR_THEME" >/dev/null 2>&1 || true
  fi

  if command -v systemctl >/dev/null 2>&1; then
    systemctl --user import-environment \
      SEVENOS_THEME_MODE GTK_THEME QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE \
      XDG_CURRENT_DESKTOP XDG_SESSION_TYPE ELECTRON_OZONE_PLATFORM_HINT >/dev/null 2>&1 || true
  fi
  if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment --systemd \
      SEVENOS_THEME_MODE GTK_THEME QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE \
      XDG_CURRENT_DESKTOP XDG_SESSION_TYPE ELECTRON_OZONE_PLATFORM_HINT >/dev/null 2>&1 || true
  fi
}

doctor() {
  local pref runtime color expected_color gtk_runtime gtk_ini gtk_hypr ozone_hypr state
  pref="$(theme_pref)"
  runtime="$(runtime_mode)"
  expected_color="prefer-dark"
  [[ "$pref" == "light" ]] && expected_color="prefer-light"
  color="$(gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null | tr -d "'" || true)"
  gtk_runtime="$(runtime_value SEVENOS_GTK_THEME)"
  gtk_ini="$(gtk_ini_value gtk-theme-name)"
  gtk_hypr="$(hypr_env_value GTK_THEME)"
  ozone_hypr="$(hypr_env_value ELECTRON_OZONE_PLATFORM_HINT)"
  state="ok"
  [[ -n "$runtime" && "$runtime" != "$pref" ]] && state="attention"
  [[ -n "$color" && "$color" != "$expected_color" ]] && state="attention"
  [[ -n "$gtk_runtime" && -n "$gtk_ini" && "$gtk_runtime" != "$gtk_ini" ]] && state="attention"
  [[ -n "$gtk_runtime" && -n "$gtk_hypr" && "$gtk_runtime" != "$gtk_hypr" ]] && state="attention"
  [[ "$ozone_hypr" != "auto" ]] && state="attention"
  STATE="$state" PREF="$pref" RUNTIME="$runtime" COLOR="$color" EXPECTED="$expected_color" GTK_RUNTIME="$gtk_runtime" GTK_INI="$gtk_ini" GTK_HYPR="$gtk_hypr" OZONE="$ozone_hypr" HYPR_ENV="$HYPR_THEME_ENV" python - <<'PY'
import json
import os

checks = {
  "runtime_matches_preference": (not os.environ.get("RUNTIME") or os.environ["RUNTIME"] == os.environ["PREF"]),
  "gsettings_color_scheme": os.environ.get("COLOR") == os.environ.get("EXPECTED"),
  "gtk_settings_match_runtime": (not os.environ.get("GTK_RUNTIME") or not os.environ.get("GTK_INI") or os.environ["GTK_RUNTIME"] == os.environ["GTK_INI"]),
  "hyprland_env_matches_runtime": (not os.environ.get("GTK_RUNTIME") or not os.environ.get("GTK_HYPR") or os.environ["GTK_RUNTIME"] == os.environ["GTK_HYPR"]),
  "electron_hint_ready": os.environ.get("OZONE") == "auto",
}
print(json.dumps({
  "schema": "sevenos.theme-session.v1",
  "state": os.environ["STATE"],
  "preferred": os.environ["PREF"],
  "runtime": os.environ["RUNTIME"],
  "expected_color_scheme": os.environ["EXPECTED"],
  "gsettings_color_scheme": os.environ["COLOR"],
  "gtk_runtime": os.environ["GTK_RUNTIME"],
  "gtk_settings": os.environ["GTK_INI"],
  "hyprland_gtk_theme": os.environ["GTK_HYPR"],
  "electron_ozone_hint": os.environ["OZONE"],
  "hypr_env": os.environ["HYPR_ENV"],
  "checks": checks,
}, indent=2))
PY
}

case "${1:-sync}" in
  sync)
    pref="$(theme_pref)"
    runtime="$(runtime_mode)"
    if [[ "$runtime" != "$pref" && -x "$ROOT_DIR/scripts/apply-theme.sh" ]]; then
      "$ROOT_DIR/scripts/apply-theme.sh" current >/tmp/sevenos-theme-session.log 2>&1 || true
    fi
    sync_env
    ;;
  doctor|status|--json)
    doctor
    ;;
  *)
    printf 'Usage: %s [sync|doctor]\n' "$0" >&2
    exit 2
    ;;
esac
