#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="${SEVENOS_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
source "$ROOT_DIR/scripts/lib.sh"
export PATH="$HOME/.cargo/bin:$PATH"

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/sevenos"
SEVENOS_CONFIG_DIR="$CONFIG_HOME/sevenos"
SEVENOS_IDENTITY_DIR="$DATA_HOME/sevenos/identity"
HYPR_DYNAMIC_CONF="$CONFIG_HOME/hypr/conf/sevenos-dynamic.conf"
THEME_JSON="$SEVENOS_CONFIG_DIR/wallpaper-theme.json"
THEME_CSS="$SEVENOS_IDENTITY_DIR/wallpaper-colors.css"
LOG_FILE="$STATE_DIR/wallpaper-theme.log"

theme_mode() {
  if [[ -f "$SEVENOS_CONFIG_DIR/theme.conf" ]]; then
    # shellcheck disable=SC1090
    source "$SEVENOS_CONFIG_DIR/theme.conf" || true
  fi
  printf '%s' "${SEVENOS_THEME_MODE:-dark}"
}

fallback_json() {
  python - <<'PY'
import json
print(json.dumps({
    "schema": "sevenos.wallpaper-theme.v1",
    "source": "fallback",
    "colors": {
        "background": "#11111B",
        "surface": "#1E1E2E",
        "text": "#CDD6F4",
        "accent": "#89B4FA",
        "secondary": "#8B7CFF",
        "cyan": "#94E2D5",
    },
}, indent=2))
PY
}

matugen_json() {
  local image="$1"
  local mode="$2"
  if ! command -v matugen >/dev/null 2>&1; then
    return 1
  fi
  matugen image "$image" --mode "$mode" --prefer saturation --json hex --dry-run --quiet
}

normalize_theme_json() {
  local source="$1"
  local json_file="$2"
  python - "$source" "$json_file" <<'PY'
import json
import sys

source = sys.argv[1]
with open(sys.argv[2], "r", encoding="utf-8") as handle:
    payload = json.load(handle)

def color(path, fallback):
    node = payload
    try:
        for item in path:
            node = node[item]
        return str(node)
    except Exception:
        return fallback

colors = {
    "background": color(["colors", "dark", "background"], color(["base16", "base00", "dark", "color"], "#11111B")),
    "surface": color(["colors", "dark", "surface_container"], color(["base16", "base01", "dark", "color"], "#1E1E2E")),
    "text": color(["colors", "dark", "on_surface"], color(["base16", "base07", "dark", "color"], "#CDD6F4")),
    "accent": color(["colors", "dark", "primary"], color(["base16", "base0D", "dark", "color"], "#89B4FA")),
    "secondary": color(["colors", "dark", "secondary"], color(["base16", "base0E", "dark", "color"], "#8B7CFF")),
    "cyan": color(["colors", "dark", "tertiary"], color(["base16", "base0C", "dark", "color"], "#94E2D5")),
}
print(json.dumps({
    "schema": "sevenos.wallpaper-theme.v1",
    "source": source,
    "colors": colors,
}, indent=2))
PY
}

write_outputs() {
  local image="$1"
  local tmp_json="$2"
  mkdir -p "$SEVENOS_CONFIG_DIR" "$SEVENOS_IDENTITY_DIR" "$(dirname -- "$HYPR_DYNAMIC_CONF")" "$STATE_DIR"

  python - "$image" "$tmp_json" "$THEME_JSON" "$THEME_CSS" "$HYPR_DYNAMIC_CONF" <<'PY'
import json
import pathlib
import sys
import time

image = pathlib.Path(sys.argv[1])
src = pathlib.Path(sys.argv[2])
theme_json = pathlib.Path(sys.argv[3])
theme_css = pathlib.Path(sys.argv[4])
hypr_conf = pathlib.Path(sys.argv[5])

payload = json.loads(src.read_text(encoding="utf-8"))
colors = payload.get("colors", {})

def c(name, fallback):
    value = str(colors.get(name) or fallback).strip()
    if not value.startswith("#"):
        value = "#" + value
    return value[:7]

background = c("background", "#11111B")
surface = c("surface", "#1E1E2E")
text = c("text", "#CDD6F4")
accent = c("accent", "#89B4FA")
secondary = c("secondary", "#8B7CFF")
cyan = c("cyan", "#94E2D5")

runtime = {
    "schema": "sevenos.wallpaper-theme.v1",
    "generated_at": int(time.time()),
    "image": str(image),
    "source": payload.get("source", "unknown"),
    "colors": {
        "background": background,
        "surface": surface,
        "text": text,
        "accent": accent,
        "secondary": secondary,
        "cyan": cyan,
    },
}
theme_json.write_text(json.dumps(runtime, indent=2) + "\n", encoding="utf-8")
theme_css.write_text(f""":root {{
  --wallpaper-bg: {background};
  --wallpaper-surface: {surface};
  --wallpaper-text: {text};
  --wallpaper-accent: {accent};
  --wallpaper-secondary: {secondary};
  --wallpaper-cyan: {cyan};
}}
""", encoding="utf-8")

def hypr_rgba(hex_color, alpha):
    return hex_color.lstrip("#") + alpha

hypr_conf.write_text(f"""# Generated by SevenOS wallpaper-theme.
# Source: {image}

general {{
    col.active_border = rgba({hypr_rgba(accent, "cc")}) rgba({hypr_rgba(secondary, "b0")}) rgba({hypr_rgba(cyan, "aa")}) 45deg
    col.inactive_border = rgba({hypr_rgba(surface, "55")})
}}

decoration {{
    blur {{
        vibrancy = 0.20
        contrast = 0.98
    }}
}}
""", encoding="utf-8")
PY
}

run_wallust() {
  local image="$1"
  if command -v wallust >/dev/null 2>&1; then
    wallust run "$image" >/dev/null 2>&1 || true
  fi
}

generate() {
  local image="${1:-}"
  local mode tmp raw
  if [[ -z "$image" || ! -f "$image" ]]; then
    log_error "Wallpaper image not found: ${image:-missing}"
    exit 1
  fi

  mode="$(theme_mode)"
  tmp="$(mktemp)"
  raw="$(mktemp)"
  if matugen_json "$image" "$mode" > "$raw" 2>>"$LOG_FILE"; then
    normalize_theme_json "matugen" "$raw" > "$tmp"
  else
    fallback_json > "$tmp"
  fi
  write_outputs "$image" "$tmp"
  run_wallust "$image"
  rm -f "$tmp" "$raw"

  if command -v hyprctl >/dev/null 2>&1 && [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]]; then
    hyprctl reload >/dev/null 2>&1 || true
  fi
}

status() {
  printf 'SevenOS wallpaper theme\n'
  printf '  matugen:        %s\n' "$(command -v matugen || printf MISS)"
  printf '  wallust:        %s\n' "$(command -v wallust || printf MISS)"
  printf '  theme json:     %s\n' "$THEME_JSON"
  printf '  theme css:      %s\n' "$THEME_CSS"
  printf '  hypr dynamic:   %s\n' "$HYPR_DYNAMIC_CONF"
  [[ -f "$THEME_JSON" ]] && sed 's/^/  /' "$THEME_JSON"
}

case "${1:-generate}" in
  generate) generate "${2:-}" ;;
  status) status ;;
  *) printf 'Usage: wallpaper-theme.sh [generate IMAGE|status]\n' >&2; exit 1 ;;
esac
