#!/usr/bin/env bash

SEVENOS_VOID="#070a18"
SEVENOS_MIDNIGHT="#10142a"
SEVENOS_PALACE="#1a1134"
SEVENOS_KENTE_GOLD="#f5b83d"
SEVENOS_SUNFIRE="#ff6b35"
SEVENOS_HIBISCUS="#d7266a"
SEVENOS_NILE="#00b8c8"
SEVENOS_EMERALD="#18a058"
SEVENOS_IVORY="#fff4dd"
SEVENOS_RAFFIA="#d8bf8a"
SEVENOS_INK="#050611"

# Backward-compatible aliases for older scripts/docs.
SEVENOS_OBSIDIAN="$SEVENOS_VOID"
SEVENOS_CHARCOAL="$SEVENOS_MIDNIGHT"
SEVENOS_SOIL="$SEVENOS_PALACE"
SEVENOS_CLAY="$SEVENOS_SUNFIRE"
SEVENOS_GOLD="$SEVENOS_KENTE_GOLD"
SEVENOS_SAND="$SEVENOS_IVORY"
SEVENOS_BAOBAB="$SEVENOS_EMERALD"
SEVENOS_INDIGO="$SEVENOS_NILE"
