#!/usr/bin/env bash

SEVENOS_INK="#07090b"
SEVENOS_GRAPHITE="#10161d"
SEVENOS_SURFACE="#17212b"
SEVENOS_PANEL="#1f2b35"
SEVENOS_BRASS="#d7b46a"
SEVENOS_COPPER="#c47a3c"
SEVENOS_MALACHITE="#2e8b6d"
SEVENOS_COBALT="#2f5d8c"
SEVENOS_OXBLOOD="#7a2e3a"
SEVENOS_IVORY="#ede3d1"
SEVENOS_RAFFIA="#bca77d"
SEVENOS_SHADOW="#030405"

# Current design direction aliases.
SEVENOS_VOID="$SEVENOS_INK"
SEVENOS_MIDNIGHT="$SEVENOS_GRAPHITE"
SEVENOS_PALACE="$SEVENOS_SURFACE"
SEVENOS_KENTE_GOLD="$SEVENOS_BRASS"
SEVENOS_SUNFIRE="$SEVENOS_COPPER"
SEVENOS_HIBISCUS="$SEVENOS_OXBLOOD"
SEVENOS_NILE="$SEVENOS_COBALT"
SEVENOS_EMERALD="$SEVENOS_MALACHITE"

# Backward-compatible aliases for older scripts/docs.
SEVENOS_OBSIDIAN="$SEVENOS_VOID"
SEVENOS_CHARCOAL="$SEVENOS_MIDNIGHT"
SEVENOS_SOIL="$SEVENOS_PALACE"
SEVENOS_CLAY="$SEVENOS_SUNFIRE"
SEVENOS_GOLD="$SEVENOS_KENTE_GOLD"
SEVENOS_SAND="$SEVENOS_IVORY"
SEVENOS_BAOBAB="$SEVENOS_EMERALD"
SEVENOS_INDIGO="$SEVENOS_NILE"
