# SevenOS Calamares settings scaffold
#
# This file documents the intended module order. It is intentionally conservative
# while SevenOS is still moving from post-install layer to installable distro.

modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - bootloader
      - packages
      - shellprocess
      - umount
  - show:
      - finished

branding: sevenos
prompt-install: false
dont-chroot: false
oem-setup: false
