# SevenOS Calamares settings scaffold
#
# This file documents the intended module order. It is intentionally conservative
# while SevenOS is still moving from post-install layer to installable distro.

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - module: shellprocess
    id: livecleanup
    config: shellprocess-livecleanup.conf
  - module: shellprocess
    id: finalize
    config: shellprocess.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@livecleanup
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - hwclock
      - bootloader
      - shellprocess@finalize
      - umount
  - show:
      - finished

branding: sevenos
prompt-install: false
dont-chroot: false
oem-setup: false
