#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="${SEVENOS_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}"
source "$ROOT_DIR/scripts/lib.sh"
source "$ROOT_DIR/installer/lib.sh"

OUT_DIR="$ROOT_DIR/out/installer"
PLAN_FILE="$OUT_DIR/sevenos-install-plan.conf"

installer_default_plan

usage() {
  cat <<'EOF'
SevenOS installer planner

Usage:
  ./install.sh installer-plan [--dry-run]

This creates an installation plan only. It does not partition, format,
mount, or install anything.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --dry-run) export SEVENOS_DRY_RUN=1 ;;
    -h|--help) usage; exit 0 ;;
    *) log_error "Unknown option: $arg"; usage; exit 1 ;;
  esac
done

ask_text() {
  local prompt="$1"
  local default="$2"
  local value

  if is_dry_run; then
    printf '%s\n' "$default"
    return 0
  fi

  read -r -p "$prompt [$default]: " value
  printf '%s\n' "${value:-$default}"
}

ask_yes_no() {
  local prompt="$1"
  local default="$2"
  local value

  if is_dry_run; then
    case "$default" in
      y|Y|yes|YES|Yes) printf 'yes\n' ;;
      *) printf 'no\n' ;;
    esac
    return 0
  fi

  read -r -p "$prompt [$default]: " value
  value="${value:-$default}"

  case "$value" in
    y|Y|yes|YES|Yes) printf 'yes\n' ;;
    *) printf 'no\n' ;;
  esac
}

ask_choice() {
  local prompt="$1"
  local default="$2"
  local choices="$3"
  local value

  if is_dry_run; then
    printf '%s\n' "$default"
    return 0
  fi

  while true; do
    read -r -p "$prompt ($choices) [$default]: " value
    value="${value:-$default}"
    case ",$choices," in
      *,"$value",*) printf '%s\n' "$value"; return 0 ;;
      *) log_warn "Choose one of: $choices" ;;
    esac
  done
}

select_disk() {
  local disks
  disks="$(lsblk -dpno NAME,SIZE,MODEL,TYPE | awk '$NF == "disk" {print}' || true)"

  if is_dry_run; then
    printf '/dev/sdX\n'
    return 0
  fi

  if [[ -z "$disks" ]]; then
    log_error "No target disks detected."
    exit 1
  fi

  printf 'Available disks:\n%s\n\n' "$disks"
  ask_text "Target disk" "/dev/sda"
}

select_profiles() {
  local profiles=()
  local answer

  answer="$(ask_yes_no "Enable DEV profile? y/n" "y")"
  [[ "$answer" == "yes" ]] && profiles+=("dev")

  answer="$(ask_yes_no "Enable CYBERSECURITY profile? y/n" "n")"
  [[ "$answer" == "yes" ]] && profiles+=("cybersecurity")

  answer="$(ask_yes_no "Enable CREATION profile? y/n" "n")"
  [[ "$answer" == "yes" ]] && profiles+=("creation")

  answer="$(ask_yes_no "Enable WINDOWS compatibility profile? y/n" "n")"
  [[ "$answer" == "yes" ]] && profiles+=("windows")

  if [[ "${#profiles[@]}" -eq 0 ]]; then
    printf 'base\n'
  else
    (IFS=,; printf '%s\n' "${profiles[*]}")
  fi
}

write_plan() {
  local target_disk="$1"
  local hostname="$2"
  local username="$3"
  local luks="$4"
  local profiles="$5"
  local filesystem="$6"
  local bootloader="$7"
  local timezone="$8"
  local locale="$9"
  local keymap="${10}"
  local swap="${11}"

  if is_dry_run; then
    printf 'mkdir -p %q\n' "$OUT_DIR"
    printf 'write install plan to %q\n' "$PLAN_FILE"
    printf 'target_disk=%q\nhostname=%q\nusername=%q\nluks=%q\nprofiles=%q\nfilesystem=%q\nbootloader=%q\ntimezone=%q\nlocale=%q\nkeymap=%q\nswap=%q\n' \
      "$target_disk" "$hostname" "$username" "$luks" "$profiles" "$filesystem" "$bootloader" "$timezone" "$locale" "$keymap" "$swap"
    return 0
  fi

  mkdir -p "$OUT_DIR"
  {
    printf '# SevenOS install plan\n'
    printf '# Generated by installer/plan.sh\n'
    printf 'target_disk=%q\n' "$target_disk"
    printf 'hostname=%q\n' "$hostname"
    printf 'username=%q\n' "$username"
    printf 'luks=%q\n' "$luks"
    printf 'profiles=%q\n' "$profiles"
    printf 'filesystem=%q\n' "$filesystem"
    printf 'bootloader=%q\n' "$bootloader"
    printf 'timezone=%q\n' "$timezone"
    printf 'locale=%q\n' "$locale"
    printf 'keymap=%q\n' "$keymap"
    printf 'swap=%q\n' "$swap"
  } > "$PLAN_FILE"
}

log_info "SevenOS installer planner"
log_warn "This planner is non-destructive. It only writes an install plan."

target_disk="$(select_disk)"
hostname="$(ask_text "Hostname" "$hostname")"
username="$(ask_text "Username" "$username")"
luks="$(ask_yes_no "Enable LUKS disk encryption? y/n" "y")"
filesystem="$(ask_choice "Filesystem" "$filesystem" "btrfs,ext4")"
bootloader="$(ask_choice "Bootloader" "$bootloader" "systemd-boot,grub")"
timezone="$(ask_text "Timezone" "$timezone")"
locale="$(ask_choice "Locale" "$locale" "${available_locales:-en_US.UTF-8,fr_FR.UTF-8}")"
keymap="$(ask_text "Keymap" "$keymap")"
swap="$(ask_choice "Swap strategy" "$swap" "zram,swapfile,none")"
profiles="$(select_profiles)"

write_plan "$target_disk" "$hostname" "$username" "$luks" "$profiles" "$filesystem" "$bootloader" "$timezone" "$locale" "$keymap" "$swap"

log_success "Install plan generated: $PLAN_FILE"
